name: Integración Continua (CI)

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: 1 obtener código
        uses: actions/checkout@v4
      
      - name: 2 configurar Node.js (20)
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      
      - name: 3 instalar dependencias
        run: npm ci
      
      - name: 4 probar el código
        run: npm test
